FROM python:3.9-slim

# Install PostgreSQL client and dependencies
RUN apt-get update && apt-get install -y \
    postgresql postgresql-contrib \
    && rm -rf /var/lib/apt/lists/*  # Clean up apt cache

WORKDIR /app

COPY app/worker.py /app/worker.py

RUN pip install flask requests

EXPOSE 5000

CMD ["python", "worker.py"]